import images from "./images";

const data = [
  {
    id: 1,
    category: "Web",
    image: images.seeFlix,
    title: "Movie Search Tool",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://seeflix.netlify.app/",
    github: "https://github.com/Juntakk/SeeFlix",
    info: "Real-time movie platform, search and find your favorite movies with all their info.",
  },
  {
    id: 2,
    category: "Mobile",
    image: images.Image1,
    title: "Reservation App",
    desc: "Java | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/Android-Camping-App",
    info: "Camping business app simulation, choose and reserve different activites.",
  },
  {
    id: 3,
    category: "Web",
    image: images.Image9,
    title: "E-Commerce",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://steem-frontend.onrender.com/",
    github: "https://github.com/Juntakk/Steem",
    info: "Video Game E-Commerce platform, add, update, remove and buy games.",
  },
  // {
  //   id: 4,
  //   category: "Games",
  //   image: images.Image3,
  //   title: "Bullet-hell Game",
  //   desc: "C++ | Raylib",
  //   demo: "",
  //   github: "https://github.com/Juntakk/mini-game-1",
  //   info: "Survivors-like bullet-hell 2D game, fight through hordes of enemies.",
  // },
  {
    id: 4,
    category: "Web",
    image: images.Image8,
    title: "Task Management",
    desc: "ReactJS | CSS",
    demo: "https://taskbro.netlify.app/",
    github: "https://github.com/Juntakk/taskbro",
    info: "Task and event planner with theme customization. CRUD basics.",
  },
  // {
  //   id: 6,
  //   category: "Games",
  //   image: images.Image7,
  //   title: "RPG game",
  //   desc: "C++ | Raylib",
  //   demo: "",
  //   github: "https://github.com/Juntakk/mini-game-3",
  //   info: "2D top-down RPG in the making, items and inventory to come.",
  // },
  {
    id: 5,
    category: "Mobile",
    image: images.Image10,
    title: "Learning App",
    desc: "Kotlin | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/planetField",
    info: "Solar system learning app, discover and learn about planets in our galaxy.",
  },
  {
    id: 6,
    category: "Mobile",
    image: images.Image12,
    title: "Recipe App",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/meals",
    info: "Food and meal planner, view and filter through various ingredients and meal types.",
  },
  // {
  //   id: 9,
  //   category: "Mobile",
  //   image: images.Image13,
  //   title: "Chat App",
  //   desc: "Flutter",
  //   demo: "",
  //   github: "https://github.com/Juntakk/chatApp",
  //   info: "Mobile chat App prototype, login and chat with other users in real-time.",
  // },
  // {
  //   id: 10,
  //   category: "Mobile",
  //   image: images.Image14,
  //   title: "Travel App",
  //   desc: "Flutter",
  //   demo: "",
  //   github: "https://github.com/Juntakk/favoritePlaces",
  //   info: "Travel app for taking pictures of memorable places, using Riverpod as state management",
  // },
  {
    id: 7,
    category: "Mobile",
    image: images.BlogImage,
    title: "Blog App",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/blog_app",
    info: "Blog app for creating blogs, using Clean Architecture and Bloc state management.",
  },
];

export default data;
