import images from "./images";

const data = [
  {
    id: 1,
    category: "Web",
    image: images.Image6,
    title: "Films",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://seeflix.netlify.app/",
    github: "https://github.com/Juntakk/SeeFlix",
    info: "Plateforme de films en temps réel, recherchez et trouvez vos films préférés avec toutes leurs informations.",
  },
  {
    id: 2,
    category: "Mobile",
    image: images.Image1,
    title: "Camping",
    desc: "Java | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/Android-Camping-App",
    info: "Simulation d'application pour une entreprise de camping, choisissez et réservez différentes activités.",
  },
  {
    id: 3,
    category: "Web",
    image: images.Image9,
    title: "Gestion de jeux vidéo",
    desc: "ReactJS | NodeJS | MongoDB",
    demo: "https://steem-frontend.onrender.com/",
    github: "https://github.com/Juntakk/Steem",
    info: "Plateforme de commerce et gestion de jeux vidéo, ajoutez, modifiez, supprimez et achetez vos jeux préférés.",
  },
  {
    id: 4,
    category: "Jeux",
    image: images.Image3,
    title: "Jeu de Combat",
    desc: "C++ | Raylib",
    demo: "",
    github: "https://github.com/Juntakk/mini-game-1",
    info: "Jeu de type bullet-hell en 2D, combattez des hordes d'ennemis. D'autres niveaux à venir.",
  },
  {
    id: 5,
    category: "Web",
    image: images.Image8,
    title: "Gestions de tâches",
    desc: "ReactJS | CSS",
    demo: "https://taskbro.netlify.app/",
    github: "https://github.com/Juntakk/taskbro",
    info: "Planificateur de tâches et d'événements avec personnalisation des thèmes. Fonctionnalités CRUD de base.",
  },
  {
    id: 6,
    category: "Jeux",
    image: images.Image7,
    title: "Mini RPG",
    desc: "C++ | Raylib",
    demo: "",
    github: "https://github.com/Juntakk/mini-game-3",
    info: "RPG en 2D vu de dessus en cours de développement, avec des objets et un inventaire à venir.",
  },
  {
    id: 7,
    category: "Mobile",
    image: images.Image10,
    title: "Système Solaire",
    desc: "Kotlin | Android Studio | SQL",
    demo: "",
    github: "https://github.com/Juntakk/planetField",
    info: "Application éducative sur le système solaire, découvrez et apprenez sur les planètes de notre galaxie.",
  },
  {
    id: 8,
    category: "Mobile",
    image: images.Image12,
    title: "Gestion de Recettes",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/meals",
    info: "Planificateur de repas, explorez et filtrez différents ingrédients et types de repas.",
  },
  {
    id: 9,
    category: "Mobile",
    image: images.Image13,
    title: "Clône Messenger",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/chatApp",
    info: "Prototype d'application de chat mobile, connectez-vous et discutez avec d'autres utilisateurs en temps réel.",
  },
  {
    id: 10,
    category: "Mobile",
    image: images.Image14,
    title: "Souvenirs de Voyages",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/favoritePlaces",
    info: "Application de voyage pour prendre des photos de lieux mémorables, sauvegarder des photos et lieux.",
  },
  {
    id: 11,
    category: "Mobile",
    image: images.BlogImage,
    title: "Blog App",
    desc: "Flutter",
    demo: "",
    github: "https://github.com/Juntakk/blog_app",
    info: "Application pour création et visionnage de blogs, Architecture Clean et Bloc state management.",
  },
];

export default data;
